services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 127.0.0.1:5432:5432/tcp
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
